# Grid settings
tsdf_voxel_size: 0.2
tsdf_voxels_per_side: 16
# Integrator settings general
method: "projective"
truncation_distance: 0.6
min_ray_length_m: 1.0
max_ray_length_m: 10.0
max_weight: 1000
use_const_weight: true
use_weight_dropoff: false
use_sparsity_compensation_factor: false
max_consecutive_ray_collisions: 1  # Only affects the fast integrator
pointcloud_queue_size: 1000
# Integrator settings projective integrator
sensor_horizontal_resolution: 200
sensor_vertical_resolution: 32
sensor_vertical_field_of_view_degrees: 45
integrator_threads: 1
use_missing_points_for_clearing: true
# Visualization
verbose: false
color_mode: "normals"
slice_level: 1.0
publish_pointclouds: true
publish_traversable: false
publish_slices: false
update_mesh_every_n_sec: 1.0
mesh_min_weight: 1e-4
publish_tsdf_info: false

world_frame: world
use_tf_transforms: true
use_freespace_pointcloud: false
traversability_radius: 1.5
allow_clear: true
min_time_between_msgs_sec: 0.0
enable_icp: false
icp_refine_roll_pitch: false
accumulate_icp_corrections: true
