world_frame: world
use_tf_transforms: true
use_freespace_pointcloud: false
tsdf_voxels_per_side: 16
tsdf_voxel_size: 0.20
max_ray_length_m: 10.0
truncation_distance: 0.6
use_sparsity_compensation_factor: true
sparsity_compensation_factor: 20.0 #10.0
use_const_weight: true
use_weight_dropoff: false
color_mode: "normals"
verbose: false
update_mesh_every_n_sec: 1.0
mesh_min_weight: 1e-4
slice_level: 1.0
method: "fast"
publish_pointclouds: true
allow_clear: true
pointcloud_queue_size: 1000
min_time_between_msgs_sec: 0.0
#max_block_distance_from_body: FLT_MAX
publish_tsdf_info: false
publish_slices: false
publish_traversable: false
traversability_radius: 1.5
enable_icp: false
icp_refine_roll_pitch: false
accumulate_icp_corrections: true

# !!! NOT IMPLEMENTED FOR VOXBLOX !!!
# Augmentation
#augment_free_frustum_enabled: true
#free_frustum_skip: 10
#free_frustum_range: 15.0
#free_frustum_fov: [rad(2*pi), rad(pi/6)]
#free_frustum_resolution: [rad(1.0*pi/180) rad(1.0*pi/180)]
