#Config for the Planner
# General params
replan_position_threshold: 0.15
replan_yaw_threshold: 5

mapping:
  collision_radius: 0.5
  type: voxblox
  voxblox:
    # This namespace contains params specifically for voxblox
    tsdf_voxel_size: 0.2
    tsdf_voxels_per_side: 16
    method: fast
    max_ray_length_m: 5
    verbose: false
    
local_planner:
  type: rh_rrt_star
    
