#Config for the Planner
# General params
replan_position_threshold: 0.35  # m
replan_yaw_threshold: 5   # deg
republish_waypoints: true

mapping:
  type: voxblox


  voxblox:
    # This namespace contains params specifically for voxblox
    # VoxbloxMap params
    clearing_radius: 1.0
    traversability_radius: 1.5
    # Grid settings
    tsdf_voxel_size: 0.2
    tsdf_voxels_per_side: 16
    # Integrator settings: general
    method: "fast"
    truncation_distance: 0.60
    min_ray_length_m: 1.0
    max_ray_length_m: 10
    max_weight: 1000
    use_const_weight: true
    use_weight_dropoff: false
    max_consecutive_ray_collisions: 1  # Only affects the fast integrator
    pointcloud_queue_size: 2
    # Visualization
    verbose: false
    color_mode: "normals"
    slice_level: -0.5
    publish_tsdf_map: true
    publish_pointclouds: true
    publish_traversable: true
    publish_slices: true
    publish_pointclouds_on_update: true

local_planner:
  type: rh_rrt_star
  # RH-RRT-Star params
  local_sampling_radius: 5.0  # m
  global_sampling_radius: 100 # m
  min_local_points: 10
  min_path_length: 0.8  # m
  max_path_length: 2.0  # m
  path_cropping_length: 0.5 # m
  max_number_of_neighbors: 20
  maximum_rewiring_iterations: 100
  maximum_root_search_iterations: 100
  
  # Lidar Model
  ray_length: 10  # m
  vertical_fov: 45  # deg
  horizontal_fov: 360 # deg
  vertical_resolution: 32 # 64
  horizontal_resolution: 200 # 1024
  ray_step: 0 # m
  downsampling_factor: 2
  mounting_orientation_y: 0.2164396
  mounting_orientation_w: 0.976296
    
