vehicle_name: airsim_drone
state_refresh_rate: 100
ViewMode: Manual
ClockSpeed: 1.0
publish_sensor_ground_truth_transforms: true # this uses gt transform
velocity: 1.0
 
sensors:   
  Lidar:
    sensor_type: Lidar
    rate: 10
    T_B_S:
      - [0.9063078,  0.0000000, 0.4226183, 0]
      - [0.0000000,  1.0000000, 0.0000000, 0]
      - [-0.4226183, 0.0000000, 0.9063078, 0]
      - [0,0,0,1]
    NumberOfChannels: 32
    Range: 10.5  # m
    PointsPerSecond: 64000 # this should lead to 200 horizontal res (65536=1hz at 1024)
    RotationsPerSecond: 10
    VerticalFOVUpper: 22.5  # deg 
    VerticalFOVLower: -22.5  # deg
    DrawDebugPoints: false

# Drifting odometry simulator
publish_ground_truth_pose: true
ground_truth_frame_suffix: "_ground_truth"
velocity_noise_frequency_hz: 0.1
velocity_noise:
  x:
    mean: 0.0
    stddev: 0.015
  y:
    mean: 0.0
    stddev: 0.015
  z:
    mean: 0.0
    stddev: 0.005
  yaw:
    mean: 0.0
    stddev: 0.0025
